<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG6uqq5A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG6uqq5A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG6uqq5A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG6uqq5A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG6uqq5A\App_KernelDevDebugContainer([
    'container.build_hash' => 'G6uqq5A',
    'container.build_id' => 'ef97f55f',
    'container.build_time' => 1699541541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG6uqq5A');
